### ISSUE TITLE
Estimating error term variance prior scale

### ISSUE THREAD

**Issue by donotdespair** [donotdespair/Bayesian-Autoregressions#4]
Hey @IoTiFeelo

Please, provide inputs to the [Estimating error term variance prior scale](https://donotdespair.github.io/Bayesian-Autoregressions/#estimating-error-term-variance-prior-scale) section of the doc.

Please include the following parts:

1. State the ig2-gamma prior as the hierarchical prior in which the scalar scale of the IG2 prior for vector $\sigma^2$ follows a gamma distribution $$\underline{s}_{\sigma^2}\sim G(s,a)$$
2. Describe briefly a Gibbs sampler in which one step is the normal-ig2 for $\boldsymbol\alpha$ and $\sigma^2$ and the other is the gamma for $\underline{s}_{\sigma^2}$
3. State the gamma full conditional posterior and its parameters
4. Present R code to sample from the gamma distribution

Introduce the material using the notation in line with that established in section [Autoregressions](https://donotdespair.github.io/Bayesian-Autoregressions/#autoregressions).

Please, create a Pull Request and include there all your commits containing contributions to this section. In your commits, please, include changes only to the `index.qmd` file. Could you make your submission clear, making instructive comments on the individual commits? If you're planning to introduce changes to other parts of the website, you're welcome to do that in a separate pull request. This would require you either to play with the branches to which you commit changes in GitHub Desktop, or to wait with introducing changes to other parts of the page later on, when you submit the Pull Request about your section.

**Comment by donotdespair** [comment]
Hi @IoTiFeelo 

Thank you so much for the submission! I really appreciate it. It was concise and included the necessary material. There was a typo in the derivation of the scale, though.

In my edit, I edited way much more than was necessary. I did that due to the compatibility with the rest of the article.

Thanks so much! T

**Comment by IoTiFeelo** [comment]
Hello @donotdespair thank you again for your patience and help, I got distracted and committed from my branch instead of the assignment's one. 

Thanks again,

Filippo
